name: CI/CD
on:
  push:
    branches: [main, master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt 
      - name: Code Analysis
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
