name: CI/CD
on:
  push:
    branches: [main, master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      - uses: actions/setup-python@v2  
      - run: pip install -r requirements.txt  # install requirements to enable GitHub run tests
      - run:  python app.py
